### ISSUE TITLE
Create anonymous survey with more time

### ISSUE THREAD

**Issue by osowiecki** [bobb34/QST#1]
Hi,
Is it possible to create a survey for people without an account, or one account used by multiple users that can last a couple of days?
I need to gather feedback from a group of people that are not necessarily using the QST system.

**Comment by bobb34** [comment]
Sorry for the late response. The secure nature of QST does not allow for unregistered users. You could create: user1/password1, user2/password2, user3/password3 and send those out to each individual user. Surveys are anonymous, so you only see if someone has taken it.
